from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path, PurePosixPath

from ..shared.config import Config, render_env_file
from .transport import (
    build_rsync_push_command,
    build_ssh_command,
    remote_runner_module_root,
    remote_servertool_env,
    servertool_remote_argv,
)


@dataclass(frozen=True)
class BootstrapPaths:
    local_runner_source: Path
    local_smtp_secrets_file: Path
    remote_config_dir: PurePosixPath
    remote_config_file: PurePosixPath
    remote_smtp_secrets_file: PurePosixPath
    remote_module_root: PurePosixPath
    remote_package_dir: PurePosixPath


def local_runner_source(root: Path) -> Path:
    package_dir = root / "servertool"
    if not package_dir.exists():
        raise FileNotFoundError(f"Local servertool package directory not found: {package_dir}")
    return package_dir


def bootstrap_paths(config: Config) -> BootstrapPaths:
    remote_config_dir = PurePosixPath(config.shared_home.as_posix()) / ".config" / "servertool"
    remote_smtp_secrets_file = remote_config_dir / "smtp.env"
    remote_module_root = remote_runner_module_root(config)
    return BootstrapPaths(
        local_runner_source=local_runner_source(config.root),
        local_smtp_secrets_file=config.smtp_secrets_file,
        remote_config_dir=remote_config_dir,
        remote_config_file=remote_config_dir / "config.env",
        remote_smtp_secrets_file=remote_smtp_secrets_file,
        remote_module_root=remote_module_root,
        remote_package_dir=remote_module_root / "servertool",
    )


def render_remote_runner_config(config: Config, paths: BootstrapPaths) -> str:
    return render_env_file(
        [
            ("SERVERTOOL_SHARED_ACCOUNT", config.shared_account),
            ("SERVERTOOL_SHARED_HOME", config.shared_home.as_posix()),
            ("SERVERTOOL_WORKSPACE_NAME", config.workspace_name),
            ("SERVERTOOL_REMOTE_ROOT", config.remote_root),
            ("SERVERTOOL_RUNNER_ROOT", config.remote_root),
            ("SERVERTOOL_NOTIFY_EMAIL_FROM", config.notify_email_from),
            ("SERVERTOOL_NOTIFY_EMAIL_TO", config.notify_email_to),
            ("SERVERTOOL_SMTP_HOST", config.smtp_host),
            ("SERVERTOOL_SMTP_PORT", str(config.smtp_port)),
            ("SERVERTOOL_SMTP_USE_SSL", "1" if config.smtp_use_ssl else "0"),
            ("SERVERTOOL_SMTP_SECRETS_FILE", paths.remote_smtp_secrets_file.as_posix()),
        ],
        comments=(
            "# Runner-side servertool configuration.",
            "# Generated by 'servertool remote bootstrap'.",
            "# Keep SMTP secrets in the separate smtp.env file.",
        ),
    )


def build_install_runner_commands(config: Config, paths: BootstrapPaths) -> list[tuple[str, list[str]]]:
    return [
        (
            "Create remote runner directory",
            build_ssh_command(
                config,
                ["mkdir", "-p", paths.remote_module_root.as_posix(), paths.remote_package_dir.as_posix()],
            ),
        ),
        (
            "Sync servertool package",
            build_rsync_push_command(
                config,
                paths.local_runner_source,
                paths.remote_package_dir,
                contents_only=True,
                extra_args=("--delete",),
            ),
        ),
        (
            "Verify remote runner",
            build_ssh_command(
                config,
                servertool_remote_argv(
                    config,
                    ["version"],
                    env=remote_servertool_env(config),
                ),
            ),
        ),
    ]


def build_bootstrap_commands(
    config: Config,
    paths: BootstrapPaths,
    runner_config_path: Path,
    smtp_source_path: Path | None,
) -> list[tuple[str, list[str]]]:
    remote_dirs = [
        config.remote_root,
        paths.remote_module_root.as_posix(),
        paths.remote_package_dir.as_posix(),
        paths.remote_config_dir.as_posix(),
    ]
    commands: list[tuple[str, list[str]]] = [
        (
            "Create remote bootstrap directories",
            build_ssh_command(config, ["mkdir", "-p", *remote_dirs]),
        ),
        (
            "Sync servertool package",
            build_rsync_push_command(
                config,
                paths.local_runner_source,
                paths.remote_package_dir,
                contents_only=True,
                extra_args=("--delete",),
            ),
        ),
        (
            "Upload runner config",
            build_rsync_push_command(config, runner_config_path, paths.remote_config_file, contents_only=False),
        ),
    ]
    chmod_targets = [paths.remote_config_file.as_posix()]
    if smtp_source_path is not None:
        commands.append(
            (
                "Upload SMTP secrets",
                build_rsync_push_command(
                    config,
                    smtp_source_path,
                    paths.remote_smtp_secrets_file,
                    contents_only=False,
                ),
            )
        )
        chmod_targets.append(paths.remote_smtp_secrets_file.as_posix())
    commands.extend(
        [
            (
                "Secure remote config files",
                build_ssh_command(config, ["chmod", "600", *chmod_targets]),
            ),
            (
                "Verify remote runner",
                build_ssh_command(
                    config,
                    servertool_remote_argv(
                        config,
                        ["version"],
                        env=remote_servertool_env(config),
                    ),
                ),
            ),
        ]
    )
    return commands
